export const tableau: string[][] = [
    ['Wx3', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'VIDE', 'Wx3', 'VIDE', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'Wx3'],
    ['VIDE', 'Wx2', 'VIDE', 'VIDE', 'VIDE', 'Lx3', 'VIDE', 'VIDE', 'VIDE', 'Lx3', 'VIDE', 'VIDE', 'VIDE', 'Wx2', 'VIDE'],
    ['VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE'],
    ['Lx2', 'VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE', 'Lx2'],
    ['VIDE', 'VIDE', 'VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE', 'VIDE', 'VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE', 'VIDE', 'VIDE'],
    ['VIDE', 'Lx3', 'VIDE', 'VIDE', 'VIDE', 'Lx3', 'VIDE', 'VIDE', 'VIDE', 'Lx3', 'VIDE', 'VIDE', 'VIDE', 'Lx3', 'VIDE'],
    ['VIDE', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'VIDE'],
    ['Wx3', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'Wx3'],
    ['VIDE', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'VIDE'],
    ['VIDE', 'Lx3', 'VIDE', 'VIDE', 'VIDE', 'Lx3', 'VIDE', 'VIDE', 'VIDE', 'Lx3', 'VIDE', 'VIDE', 'VIDE', 'Lx3', 'VIDE'],
    ['VIDE', 'VIDE', 'VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE', 'VIDE', 'VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE', 'VIDE', 'VIDE'],
    ['Lx2', 'VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE', 'Lx2'],
    ['VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'VIDE', 'Wx2', 'VIDE', 'VIDE'],
    ['VIDE', 'Wx2', 'VIDE', 'VIDE', 'VIDE', 'Lx3', 'VIDE', 'VIDE', 'VIDE', 'Lx3', 'VIDE', 'VIDE', 'VIDE', 'Wx2', 'VIDE'],
    ['Wx3', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'VIDE', 'Wx3', 'VIDE', 'VIDE', 'VIDE', 'Lx2', 'VIDE', 'VIDE', 'Wx3'],
];
